production:
  adapter: postgresql
  encoding: unicode
  database: travel_planning_production
  pool: 5
  username:
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: travel_planning_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: travel_planning_test
  pool: 5
  username:
  password:
