production:
  adapter: postgresql
  encoding: unicode
  database: italia_production
  pool: 5
  username: 
  password: 

development:
  adapter: postgresql
  encoding: unicode
  database: italia_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: italia_test
  pool: 5
  username: 
  password: 